version: '3'
volumes:
  dbvolume:

services:
  db:
    image: mysql:8
    volumes:
      - dbvolume:/var/lib/mysql
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: financeiro
      MYSQL_PASSWORD: root
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: philabreu/app:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:mysql://db:3306/financeiro?createDatabaseIfNotExist=true&&useSSL=false&&allowPublicKeyRetrieval=true
      spring.jpa.hibernate.ddl-auto: create
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect