spring:
  jpa:
    database: MYSQL
    hibernate.ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/financeiro?createDatabaseIfNotExist=true&&useSSL=false
    username: root
    password: root
  jackson.deserialization.fail-on-unknown-properties: true

#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

